language: objective-c
osx_image: xcode11
xcode_project: Example/ASWeekSelectorView.xcodeproj
xcode_scheme: ASWeekSelectorView
xcode_sdk: iphonesimulator13.0
env:
  global:
  - FRAMEWORK_NAME=ASWeekSelectorView
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
    - xcodebuild clean build -sdk iphonesimulator -project Example/ASWeekSelectorView.xcodeproj -scheme ASWeekSelectorView CODE_SIGNING_REQUIRED=NO
deploy:
  provider: releases
  api_key:
    secure: t7BNwlYdtueVSQBXAF+FcvjmLa3uBDXCaue3HVeFlXdA0lV04BQUpdCK6rRhfAw941LiKQxaCbfUFWAs1K4vm7AAkHhwvjdhlseG2hmlV4Jqx39g7mJAOl8s8DM5DJvvfiI764DzyUmHBNNB0l4IQ2eWzieOLBZdsdd4SrhvfkE=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: nighthawk/ASWeekSelectorView
    tags: true
